'\" t
.\"     Title: Options Common to MySQL Cluster Programs
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.6
.\"  Language: English
.\"
.TH "OPTIONS COMMON TO MY" "1" "11/15/2013" "MySQL 5\&.6" "MySQL Database System"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.\" MySQL Cluster: administration
.\" command-line options (MySQL Cluster)
.\" program options (MySQL Cluster)
.\" MySQL Cluster: ndbd
.\" MySQL Cluster: mgm
.\" MySQL Cluster: mgmd
.SH "NAME"
ndb-common-options \- MySQL Cluster Common Program Options
.SH "DESCRIPTION"
.PP
All MySQL Cluster programs accept the options described in this section, with the following exceptions:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBmysqld\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBndb_print_backup_file\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBndb_print_schema_file\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBndb_print_sys_file\fR
.RE
.PP
Users of earlier MySQL Cluster versions should note that some of these options have been changed to make them consistent with one another as well as with
\fBmysqld\fR\&. You can use the
\fB\-\-help\fR
option with any MySQL Cluster program\(emwith the exception of
\fBndb_print_backup_file\fR,
\fBndb_print_schema_file\fR, and
\fBndb_print_sys_file\fR\(emto view a list of the options which the program supports\&.
.PP
The options in the following table are common to all MySQL Cluster executables (except those noted previously in this section)\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&17.30.\ \&Common MySQL Cluster Program Options and Variables: MySQL Cluster NDB 7.3
.TS
allbox tab(:);
lB lB lB.
T{
Format
T}:T{
Description
T}:T{
Added / Removed
T}
.T&
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l.
T{
.PP
--help,
.PP
--usage,
.PP
-?
T}:T{
Display help message and exit
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--ndb-connectstring=connectstring,
.PP
--connect-string=connectstring,
.PP
-c
T}:T{
Set connection string for connecting to ndb_mgmd\&. Syntax:
            [nodeid=<id>;][host=]<hostname>[:<port>]\&.
            Overrides entries specified in NDB_CONNECTSTRING or my\&.cnf\&.
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--ndb-mgmd-host=host[:port]
T}:T{
Set the host (and port, if desired) for connecting to the management
            server
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--ndb-nodeid=#
T}:T{
Set node id for this node
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--ndb-optimized-node-selection
T}:T{
Select nodes for transactions in a more optimal way
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--character-sets-dir=path
T}:T{
Directory where character sets are
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--debug=options
T}:T{
Enable output from debug calls\&. Can be used only for versions compiled
            with debugging enabled
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--core-file
T}:T{
Write core on errors (defaults to TRUE in debug builds)
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
T{
.PP
--version,
.PP
-V
T}:T{
Output version information and exit
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
.TE
.sp 1
.PP
For options specific to individual MySQL Cluster programs, see
Section\ \&17.4, \(lqMySQL Cluster Programs\(rq\&.
.PP
See
Section\ \&17.3.4.2, \(lqMySQL Server Options for MySQL Cluster\(rq, for
\fBmysqld\fR
options relating to MySQL Cluster\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" help option (MySQL Cluster programs).\" usage option (MySQL Cluster programs).\" -? option (MySQL Cluster programs)\fB\-\-help\fR,
\fB\-\-usage\fR,
\fB\-?\fR
.TS
allbox tab(:);
l l s s
l l s s
l l s s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-help
T}
T{
\ \&
T}:T{
\-\-usage
T}
T{
\ \&
T}:T{
\-?
T}
.TE
.sp 1
Prints a short list with descriptions of the available command options\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" character-sets-dir option (MySQL Cluster programs).\" character-sets-dir option (MySQL Cluster programs)\fB\-\-character\-sets\-dir=\fR\fB\fIname\fR\fR
.TS
allbox tab(:);
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-character\-sets\-dir=path
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
file name
T}
:T{
\fBDefault\fR
T}:T{
T}
.TE
.sp 1
Tells the program where to find character set information\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" ndb-connectstring option (MySQL Cluster programs).\" connect-string option (MySQL Cluster programs).\" -c option (MySQL Cluster programs)\fB\-\-ndb\-connectstring=\fR\fB\fIconnect_string\fR\fR,
\fB\-\-connect\-string=\fR\fB\fIconnect_string\fR\fR,
\fB\-c \fR\fB\fIconnect_string\fR\fR
.TS
allbox tab(:);
l l s s
l l s s
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-ndb\-connectstring=connectstring
T}
T{
\ \&
T}:T{
\-\-connect\-string=connectstring
T}
T{
\ \&
T}:T{
\-c
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
string
T}
:T{
\fBDefault\fR
T}:T{
localhost:1186
T}
.TE
.sp 1
This option takes a MySQL Cluster connection string that specifies the management server for the application to connect to, as shown here:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBndbd \-\-ndb\-connectstring="nodeid=2;host=ndb_mgmd\&.mysql\&.com:1186"\fR
.fi
.if n \{\
.RE
.\}
.sp
For more information, see
Section\ \&17.3.2.3, \(lqMySQL Cluster Connection Strings\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" core-file option (MySQL Cluster programs)\fB\-\-core\-file\fR
.TS
allbox tab(:);
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-core\-file
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
boolean
T}
:T{
\fBDefault\fR
T}:T{
FALSE
T}
.TE
.sp 1
Write a core file if the program dies\&. The name and location of the core file are system\-dependent\&. (For MySQL Cluster programs nodes running on Linux, the default location is the program\*(Aqs working directory\(emfor a data node, this is the node\*(Aqs
DataDir\&.) For some systems, there may be restrictions or limitations; for example, it might be necessary to execute
\fBulimit \-c unlimited\fR
before starting the server\&. Consult your system documentation for detailed information\&.
.sp
If MySQL Cluster was built using the
\fB\-\-debug\fR
option for
\fBconfigure\fR, then
\fB\-\-core\-file\fR
is enabled by default\&. For regular builds,
\fB\-\-core\-file\fR
is disabled by default\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" debug option (MySQL Cluster programs)\fB\-\-debug[=\fR\fB\fIoptions\fR\fR\fB]\fR
.TS
allbox tab(:);
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-debug=options
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
string
T}
:T{
\fBDefault\fR
T}:T{
d:t:O,/tmp/ndb_restore\&.trace
T}
.TE
.sp 1
This option can be used only for versions compiled with debugging enabled\&. It is used to enable output from debug calls in the same manner as for the
\fBmysqld\fR
process\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" ndb-mgmd-host option (MySQL Cluster programs)\fB\-\-ndb\-mgmd\-host=\fR\fB\fIhost\fR\fR\fB[:\fR\fB\fIport\fR\fR\fB]\fR
.TS
allbox tab(:);
l l s s
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-ndb\-mgmd\-host=host[:port]
T}
T{
\fBOption\-File Format\fR
T}:T{
ndb\-mgmd\-host
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
string
T}
:T{
\fBDefault\fR
T}:T{
localhost:1186
T}
.TE
.sp 1
Can be used to set the host and port number of a single management server for the program to connect to\&. If the program requires node IDs or references to multiple management servers (or both) in its connection information, use the
\fB\-\-ndb\-connectstring\fR
option instead\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" ndb-nodeid option (MySQL Cluster programs)\fB\-\-ndb\-nodeid=\fR\fB\fI#\fR\fR
.TS
allbox tab(:);
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-ndb\-nodeid=#
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
numeric
T}
:T{
\fBDefault\fR
T}:T{
0
T}
.TE
.sp 1
Sets this node\*(Aqs MySQL Cluster node ID\&.
\fIThe range of permitted values depends on the node\*(Aqs type (data, management, or API) and the MySQL Cluster software version\fR\&. See
Section\ \&17.1.6.2, \(lqLimits and Differences of MySQL Cluster from Standard MySQL Limits\(rq, for more information\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" ndb-optimized-node-selection option (MySQL Cluster)\fB\-\-ndb\-optimized\-node\-selection\fR
.TS
allbox tab(:);
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-ndb\-optimized\-node\-selection
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
boolean
T}
:T{
\fBDefault\fR
T}:T{
TRUE
T}
.TE
.sp 1
Optimize selection of nodes for transactions\&. Enabled by default\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" version option (MySQL Cluster programs).\" -V option (MySQL Cluster programs)\fB\-\-version\fR,
\fB\-V\fR
.TS
allbox tab(:);
l l s s
l l s s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-version
T}
T{
\ \&
T}:T{
\-V
T}
.TE
.sp 1
Prints the MySQL Cluster version number of the executable\&. The version number is relevant because not all versions can be used together, and the MySQL Cluster startup process verifies that the versions of the binaries being used can co\-exist in the same cluster\&. This is also important when performing an online (rolling) software upgrade or downgrade of MySQL Cluster\&.
.sp
See
Section\ \&17.5.5, \(lqPerforming a Rolling Restart of a MySQL Cluster\(rq), for more information\&.
.RE
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 1997, 2013, Oracle and/or its affiliates. All rights reserved.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
