'\" t
.\"     Title: \fBndb_error_reporter\fR
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 09/09/2013
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.6
.\"  Language: English
.\"
.TH "\FBNDB_ERROR_REPORTE" "1" "09/09/2013" "MySQL 5\&.6" "MySQL Database System"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.\" ndb_error_reporter
.\" bugs: MySQL Cluster: reporting
.SH "NAME"
ndb_error_reporter \- NDB error\-reporting utility
.SH "SYNOPSIS"
.HP \w'\fBndb_error_reporter\ \fR\fB\fIoptions\fR\fR\ 'u
\fBndb_error_reporter \fR\fB\fIoptions\fR\fR
.SH "DESCRIPTION"
.PP
\fBndb_error_reporter\fR
creates an archive from data node and management node log files that can be used to help diagnose bugs or other problems with a cluster\&.
\fIIt is highly recommended that you make use of this utility when filing reports of bugs in MySQL Cluster\fR\&.
.PP
The following table includes command options specific to the MySQL Cluster program
\fBndb_error_reporter\fR\&. Additional descriptions follow the table\&. For options common to most MySQL Cluster programs (including
\fBndb_error_reporter\fR), see
Options Common to MySQL Cluster Programs(1)\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&17.20.\ \&ndb_error_reporter Options and Variables: MySQL Cluster NDB 7.3
.TS
allbox tab(:);
lB lB lB.
T{
Format
T}:T{
Description
T}:T{
Added / Removed
T}
.T&
l l l.
T{
.PP
--fs
T}:T{
Include file system data in error report; can use a large amount of disk
            space
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
.TE
.sp 1
        Usage
.sp
.if n \{\
.RS 4
.\}
.nf
ndb_error_reporter \fIpath/to/config\-file\fR [\fIusername\fR] [\-\-fs]
.fi
.if n \{\
.RE
.\}
.PP
This utility is intended for use on a management node host, and requires the path to the management host configuration file (config\&.ini)\&. Optionally, you can supply the name of a user that is able to access the cluster\*(Aqs data nodes using SSH, to copy the data node log files\&. ndb_error_reporter then includes all of these files in archive that is created in the same directory in which it is run\&. The archive is named
ndb_error_report_\fIYYYYMMDDHHMMSS\fR\&.tar\&.bz2, where
\fIYYYYMMDDHHMMSS\fR
is a datetime string\&.
.PP
If the
\fB\-\-fs\fR
is used, then the data node file systems are also copied to the management host and included in the archive that is produced by this script\&. As data node file systems can be extremely large even after being compressed, we ask that you please do
\fInot\fR
send archives created using this option to Oracle unless you are specifically requested to do so\&.
.TS
allbox tab(:);
l l s s
l l s s
^ l l s
^ l l s.
T{
\fBCommand\-Line Format\fR
T}:T{
\-\-fs
T}
T{
\ \&
T}:T{
\fBPermitted Values\fR
T}
:T{
\fBType\fR
T}:T{
boolean
T}
:T{
\fBDefault\fR
T}:T{
FALSE
T}
.TE
.sp 1
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 1997, 2013, Oracle and/or its affiliates. All rights reserved.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
