'\" t
.\"     Title: \fBndb_drop_index\fR
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 05/21/2013
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.6
.\"  Language: English
.\"
.TH "\FBNDB_DROP_INDEX\FR" "1" "05/21/2013" "MySQL 5\&.6" "MySQL Database System"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.\" ndb_drop_index
.SH "NAME"
ndb_drop_index \- drop index from an NDB table
.SH "SYNOPSIS"
.HP \w'\fBndb_drop_index\ \fR\fB\fIoptions\fR\fR\ 'u
\fBndb_drop_index \fR\fB\fIoptions\fR\fR
.SH "DESCRIPTION"
.PP
\fBndb_drop_index\fR
drops the specified index from an
NDB
table\&.
\fIIt is recommended that you use this utility only as an example for writing NDB API applications\fR\(emsee the Warning later in this section for details\&.
        Usage
.sp
.if n \{\
.RS 4
.\}
.nf
ndb_drop_index \-c \fIconnect_string\fR \fItable_name\fR \fIindex\fR \-d \fIdb_name\fR
.fi
.if n \{\
.RE
.\}
.PP
The statement shown above drops the index named
\fIindex\fR
from the
\fItable\fR
in the
\fIdatabase\fR\&.
.PP
The following table includes options that are specific to
\fBndb_drop_index\fR\&. Additional descriptions follow the table\&. For options common to most MySQL Cluster programs (including
\fBndb_drop_index\fR), see
Options Common to MySQL Cluster Programs(1)\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&17.17.\ \&ndb_drop_index Options and Variables: MySQL Cluster NDB 7.3
.TS
allbox tab(:);
lB lB lB.
T{
Format
T}:T{
Description
T}:T{
Added / Removed
T}
.T&
l l l.
T{
.PP
\-\-database=dbname,
.PP
\-d
T}:T{
Name of the database in which the table is found
T}:T{
.PP
All MySQL 5\&.6 based releases
T}
.TE
.sp 1
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBWarning\fR
.ps -1
.br
.PP
\fIOperations performed on Cluster table indexes using the NDB API are not visible to MySQL and make the table unusable by a MySQL server\fR\&. If you use this program to drop an index, then try to access the table from an SQL node, an error results, as shown here:
.sp .5v
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fB\&./ndb_drop_index \-c localhost dogs ix \-d ctest1\fR
Dropping index dogs/idx\&.\&.\&.OK
NDBT_ProgramExit: 0 \- OK
shell> \fB\&./mysql \-u jon \-p ctest1\fR
Enter password: *******
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with \-A
Welcome to the MySQL monitor\&.  Commands end with ; or \eg\&.
Your MySQL connection id is 7 to server version: 5\&.6\&.11\-ndb\-7\&.3\&.2
Type \*(Aqhelp;\*(Aq or \*(Aq\eh\*(Aq for help\&. Type \*(Aq\ec\*(Aq to clear the buffer\&.
mysql> \fBSHOW TABLES;\fR
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| Tables_in_ctest1 |
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| a                |
| bt1              |
| bt2              |
| dogs             |
| employees        |
| fish             |
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
6 rows in set (0\&.00 sec)
mysql> \fBSELECT * FROM dogs;\fR
ERROR 1296 (HY000): Got error 4243 \*(AqIndex not found\*(Aq from NDBCLUSTER
.fi
.if n \{\
.RE
.\}
.PP
In such a case, your
\fIonly\fR
option for making the table available to MySQL again is to drop the table and re\-create it\&. You can use either the SQL statementDROP TABLE
or the
\fBndb_drop_table\fR
utility (see
\fBndb_drop_table\fR(1)) to drop the table\&.
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 1997, 2013, Oracle and/or its affiliates. All rights reserved.
.PP
This software and related documentation are provided under a license agreement containing restrictions on use and disclosure and are protected by intellectual property laws. Except as expressly permitted in your license agreement or allowed by law, you may not use, copy, reproduce, translate, broadcast, modify, license, transmit, distribute, exhibit, perform, publish, or display any part, in any form, or by any means. Reverse engineering, disassembly, or decompilation of this software, unless required by law for interoperability, is prohibited.
.PP
The information contained herein is subject to change without notice and is not warranted to be error-free. If you find any errors, please report them to us in writing.
.PP
If this software or related documentation is delivered to the U.S. Government or anyone licensing it on behalf of the U.S. Government, the following notice is applicable:
.PP
U.S. GOVERNMENT RIGHTS Programs, software, databases, and related documentation and technical data delivered to U.S. Government customers are "commercial computer software" or "commercial technical data" pursuant to the applicable Federal Acquisition Regulation and agency-specific supplemental regulations. As such, the use, duplication, disclosure, modification, and adaptation shall be subject to the restrictions and license terms set forth in the applicable Government contract, and, to the extent applicable by the terms of the Government contract, the additional rights set forth in FAR 52.227-19, Commercial Computer Software License (December 2007). Oracle USA, Inc., 500 Oracle Parkway, Redwood City, CA 94065.
.PP
This software is developed for general use in a variety of information management applications. It is not developed or intended for use in any inherently dangerous applications, including applications which may create a risk of personal injury. If you use this software in dangerous applications, then you shall be responsible to take all appropriate fail-safe, backup, redundancy, and other measures to ensure the safe use of this software. Oracle Corporation and its affiliates disclaim any liability for any damages caused by use of this software in dangerous applications.
.PP
Oracle is a registered trademark of Oracle Corporation and/or its affiliates. MySQL is a trademark of Oracle Corporation and/or its affiliates, and shall not be used without Oracle's express written authorization. Other names may be trademarks of their respective owners.
.PP
This software and documentation may provide access to or information on content, products, and services from third parties. Oracle Corporation and its affiliates are not responsible for and expressly disclaim all warranties of any kind with respect to third-party content, products, and services. Oracle Corporation and its affiliates will not be responsible for any loss, costs, or damages incurred due to your access to or use of third-party content, products, or services.
.PP
This document in any form, software or printed matter, contains proprietary information that is the exclusive property of Oracle. Your access to and use of this material is subject to the terms and conditions of your Oracle Software License and Service Agreement, which has been executed and with which you agree to comply. This document and information contained herein may not be disclosed, copied, reproduced, or distributed to anyone outside Oracle without prior written consent of Oracle or as specifically provided below. This document is not part of your license agreement nor can it be incorporated into any contractual agreement with Oracle or its subsidiaries or affiliates.
.PP
This documentation is NOT distributed under a GPL license. Use of this documentation is subject to the following terms:
.PP
You may create a printed copy of this documentation solely for your own personal use. Conversion to other formats is allowed as long as the actual content is not altered or edited in any way. You shall not publish or distribute this documentation in any form or on any media, except if you distribute the documentation in a manner similar to how Oracle disseminates it (that is, electronically for download on a Web site with the software) or on a CD-ROM or similar medium, provided however that the documentation is disseminated together with the software on the same medium. Any other use, such as any dissemination of printed copies or use of this documentation, in whole or in part, in another publication, requires the prior written consent from an authorized representative of Oracle. Oracle and/or its affiliates reserve any and all rights to this documentation not expressly granted above.
.PP
For more information on the terms of this license, or for details on how the MySQL documentation is built and produced, please visit
\m[blue]\fBMySQL Contact & Questions\fR\m[].
.PP
For additional licensing information, including licenses for third-party libraries used by MySQL products, see
Preface and Legal Notices.
.PP
For help with using MySQL, please visit either the
\m[blue]\fBMySQL Forums\fR\m[]
or
\m[blue]\fBMySQL Mailing Lists\fR\m[]
where you can discuss your issues with other MySQL users.
.PP
For additional documentation on MySQL products, including translations of the documentation into other languages, and downloadable versions in variety of formats, including HTML and PDF formats, see the
\m[blue]\fBMySQL Documentation Library\fR\m[].
.sp
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
